### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by mikkoh** [Jam3/ae-to-json#9]
This issue can be finished once these issues have been finished (in no particular order):
- [x] #2 Document format details
- [x] #5 Remove `get` which comes from `after-effects` module
- [x] #6 Add shims/handling for shims
- [x] #8 Add docs for consuming NPM module
